# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: softmessage

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports: 
      - 3000:3000
    environment: 
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: example
      PGDATABASE: softmessage
      PGPORT: 5432

  migrate:
    build: ./dev
    environment: 
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: example
      PGDATABASE: softmessage
      PGPORT: 5432
